// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChangeButtonCondoController from "./change_button_condo_controller"
application.register("change-button-condo", ChangeButtonCondoController)

import ChangeButtonController from "./change_button_controller"
application.register("change-button", ChangeButtonController)

import DocumentNumberController from "./document_number_controller"
application.register("document-number", DocumentNumberController)
